/* Formatted on 4/25/2018 11:02:14 AM (QP5 v5.287) */
SELECT "DMDBASE"."DM_DAILY_DATA"."DBKEY",
       "DMDBASE"."DM_DAILY_DATA"."DAILY_DATE",
       "DMDBASE"."DM_DAILY_DATA"."VALUE",
       "DMDBASE"."KEYWORD_TAB"."DATA_TYPE",
       "DMDBASE"."KEYWORD_TAB"."XCOORD",
       "DMDBASE"."KEYWORD_TAB"."YCOORD",
       "DMDBASE"."KEYWORD_TAB"."STATION"
  FROM "DMDBASE"."DM_DAILY_DATA", "DMDBASE"."KEYWORD_TAB"
 WHERE     "DMDBASE"."DM_DAILY_DATA"."DBKEY" =
              "DMDBASE"."KEYWORD_TAB"."DBKEY"
       AND "DMDBASE"."KEYWORD_TAB"."DATA_TYPE" = 'RAIN'
       AND "DMDBASE"."KEYWORD_TAB"."XCOORD" between 300000 and 700000
       AND "DMDBASE"."KEYWORD_TAB"."YCOORD" between 450000 and 980000
       and "DMDBASE"."DM_DAILY_DATA"."DAILY_DATE" > to_date ('01/01/2002','MM/DD/YYYY')
       and "DMDBASE"."KEYWORD_TAB"."FREQUENCY" = 'DA'